//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class ViblyyKeyy
    {
        [Required(ErrorMessage = "This field is required.")]
        public int Id { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string Value { get; set; }

        [DisplayName("Expiration Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ExpirationDate { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string Type { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string Environment { get; set; }
        public string Comments { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Last Notified Date")]
        [DataType(DataType.Date)]
        public System.DateTime LastNotifiedDate { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string Application { get; set; }

        [DisplayName("SAMAccountName")]
        public string PIDName { get; set; }
    }
}
